### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Matthww** [mwvent/BuddyPets#1]
Hey.

I got a question I was looking on you're MCPE Server website and then I saw something with a script to migrate to a DB do you mean from .yml to a .sql database if yes... Do you mind to share it me :) I got to many registered people to do it by hand (more then 50 thousand)

**Comment by mwvent** [comment]
Hiya! I have a few migrations scripts I made - it depends on the plugin which one are you looking to migrate?

**Comment by Matthww** [comment]
From Simpleauth

**Comment by mwvent** [comment]
Ill see if I can find the script

**Comment by Matthww** [comment]
Thanks

**Comment by Matthww** [comment]
And could you find it?

**Comment by mwvent** [comment]
oh my god i am so sorry I absolutley thought I had replied to this !

**Comment by mwvent** [comment]
I dont have the exact script - but as I recall the table names and columns in the sqlite3 db are identical. 

so its along the lines of from a bash shell promt

sqlite3 simpleauth.db .dump > simpleauth.sql

You can strip the create table statement out of the simpleauth.sql - if you have run simpleauth plugin with your new mysql database at least once the table will have been created - just keep the INSERT statements.

Then just pipe them into mysql
cat simpleauth.sql | mysql -u yourpocketmineuser -p yourdatabasename

**Comment by mwvent** [comment]
Of course I am assuming a linux server? the script would have been no good for windows anyway even if I did still have it

**Comment by Matthww** [comment]
Yes ofc I have Linux!

**Comment by Matthww** [comment]
I made my own script :)
